### ISSUE TITLE
j.vimic~ is not building/loading

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#779]
On the dev branch j.vimic~ currently does not compile properly, and it does not load in Max.

The dsp.externals.loading.maxtest.maxpat integration test can be used to examine this issue.

**Comment by lossius** [comment]
This fails due to a missing header file referenced in CrossFadeQueue.cpp: 

#include <Multiprocessing.h>

Multiprocessing.h not found.

According to this thread:

http://www.justskins.com/forums/multiprocessing-h-issue-155620.html

Multiprocessing.h seems to be a OS9 file, and now should be substituted for

#include <CoreServices/CoreServices.h>

I'm currently trying this out.

**Comment by lossius** [comment]
I tried substituting and then testing the object in Max 7, but I quickly got a spinning beach ball once I started audio. @Nilson I'll assign this issue to you. I guess this will need to be fixed as part of a larger operation to port all vimic modules to Jamoma 0.6. That again should be linked to a more general process of reviewing how spatialisation models might best be done in Jamoma 0.6.

**Comment by tap** [comment]
This object builds fine on the tap/cleanup branch, FWIW.  There are other things not ready for prime-time on that branch though...

**Comment by lossius** [comment]
Thanks, I've cherry-picked d243023ccda44b992af6c413d5906ecbdb7640fb, and that seems to solve the problem.

**Comment by jcelerier** [comment]
Mhh... On my machine (Yosemite) without `Multiprocessing.hpp`, the build fails :
    In file included from /j.vimic~/CrossFadeQueue.cpp:20:
    c74support/max-includes/ext_critical.h:16:9: error:
      unknown type name 'MPCriticalRegionID'
    typedef MPCriticalRegionID t_critical;  ///< a critical region  @ingrou...

However including 
    #include <CoreServices/CoreServices.h>
instead solves the problem.

**Comment by lossius** [comment]
That compiles on OSX 10.10 as well. I'll commit the change.
